# I'll take all airports of the world from this dataset

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv ("input/starbucks.csv")

In [4]:
# https://www.kaggle.com/open-flights/airports-train-stations-and-ferry-terminals#airports-extended.csv

In [5]:
null_cols = data.isnull().sum()
drop_cols = list(null_cols[null_cols > 35000].index)
data_clean1 = data.drop(drop_cols, axis=1)
data.dropna()

,Brand,Store Number,Store Name,Ownership Type,Street Address,City,State/Province,Country,Postcode,Phone Number,Timezone,Longitude,Latitude
0,Starbucks,47370-257954,"Meritxell, 96",Licensed,"Av. Meritxell, 96",Andorra la Vella,7,AD,AD500,376818720,GMT+1:00 Europe/Andorra,1.53,42.51
11,Starbucks,1579-122101,HCT Abu Dhabi Women's College Block,Licensed,"Najda Street, Higher Colleges of Technology",Abu Dhabi,AZ,AE,3167,26426280,GMT+04:00 Asia/Dubai,54.37,24.49
12,Starbucks,32595-122105,Standard Chartered Building,Licensed,"Khalidiya St., Beside Union Cooperative Society",Abu Dhabi,AZ,AE,3167,26359275,GMT+04:00 Asia/Muscat,55.69,24.19
20,Starbucks,32767-131566,Shangri-La Souq,Licensed,"Shangri-La Souk, Um Al Nar",Abu Dhabi,AZ,AE,3167,25581641,GMT+04:00 Asia/Dubai,54.51,24.42
45,Starbucks,32640-131563,Tawam Hospital,Licensed,"Al Ain Abu Dhabi Rd, Khalifa Bin Zayed, Al Mak...",Al Ain,AZ,AE,3167,37677581,GMT+04:00 Asia/Muscat,55.65,24.19
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25594,Starbucks,27082-246744,Emart,Licensed,"168 Phan Văn Trị, Quận Gò Vấp, Khách sạn Rex",Thành Phố Hồ Chí Minh,SG,VN,70000,08 3588 0146,GMT+000000 Asia/Saigon,106.69,10.82
25595,Starbucks,21401-212072,Rex,Licensed,"141 Nguyễn Huệ, Quận 1, Góc đường Pasteur và L...",Thành Phố Hồ Chí Minh,SG,VN,70000,08 3824 4668,GMT+000000 Asia/Saigon,106.70,10.78
25596,Starbucks,24010-226985,Panorama,Licensed,"SN-44, Tòa Nhà Panorama, 208 Trần Văn Trà, Quận 7",Thành Phố Hồ Chí Minh,SG,VN,70000,08 5413 8292,GMT+000000 Asia/Saigon,106.71,10.72
25597,Starbucks,47608-253804,Rosebank Mall,Licensed,"Cnr Tyrwhitt and Cradock Avenue, Rosebank",Johannesburg,GT,ZA,2194,27873500159,GMT+000000 Africa/Johannesburg,28.04,-26.15
25599,Starbucks,47609-253286,Mall of Africa,Licensed,"Shop 2077, Upper Level, Waterfall City",Midrand,GT,ZA,1682,27873500215,GMT+000000 Africa/Johannesburg,28.11,-26.02

## Finding out the "real" name of columns to work it

In [6]:
col_names=[]
for e in data:
    col_names.append(e)
col_names

['Brand',
 'Store Number',
 'Store Name',
 'Ownership Type',
 'Street Address',
 'City',
 'State/Province',
 'Country',
 'Postcode',
 'Phone Number',
 'Timezone',
 'Longitude',
 'Latitude']

In [7]:
starbucks=[]
for e in data["Store Name"]:
    starbucks.append(e)

In [8]:
star_long=[]
star_lat=[]
for e in data["Longitude"]:
    star_long.append(e)
for e in data["Latitude"]:
    star_lat.append(e)

I have some str-types that I must turn into float

In [9]:
def type_conversor(x):
    for e in x:
        e=float(e)
    return

In [10]:
type_conversor(star_long)
type_conversor(star_lat)

# I'll call this list from main.ipynb to find the closest airport to each office

In [11]:
starbucks
%store starbucks
star_lat
%store star_lat
star_long
%store star_long

Stored 'starbucks' (list)
Stored 'star_lat' (list)
Stored 'star_long' (list)